# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "PtfCRF3/kp8uW43HijEFmCPUHJasxh6cByRU3A+t6NZLQXzZirLu0w2IoLpLxRoYCHMxFB8h0/ASzl5V9PjLRC2A1f4o4nFTBWBancAGYnqq8+hsciVW19fJ3G6su1hLrozens45IABIZhBDG7V5D9Sw9X6Flu2QyPl5duWdPLJ904DGbrZ6hglE1uwl6+R8TKWOyNEWs7sXDIIRbTQZdUBc3hHnCjHERliBfuwfJuwLZD6TF4bPW4dt7J0nBmmNvQvUVyxkXdgiFWfJLxIEiL9ET9sn1nQb5QNfOzvD1tJ1j8fskaR8Ak7WbuTuIhnSgFh6Icsf11+YfHtuB8a66V06+PI/1GL3Ivk1HqJIvCVp3XQO0EhJqLB1lQ2iaraw1BBEze7+i8iSj/6Qwj9CWGFvi0aFQoMWrLyRKbQ6pJLf8xREB2q1JRzIh1o92VyatUULTDJfzgokwmV/KdzxXL8+xI6TwjlqhStgjd3kaPB015jliEUVQBtzfPcP9YwHFJ++FaioSF/aJBy7UX8/HdyEYLDRA8J1GVHdu38fQnwCDWHhaKPBMrJlPOBLpi+2VSOcbsB0smhEqF1ry+AU7s9CTgidxDs5CtM+Y+ONZALb7uBSCX0RvOO1yE4i/1fZ/UbZECz/r5xCW+hGz5IaJJVkIh3QoJfElB56H6ATt0o="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
