travis:
  secure:
    BINSTAR_TOKEN: pkuBSgeZHylK03RAgkhqVCfHFQtNdvo4eqR2kwqIE4MUA/7u1HSV/48XHF6epMcU9INYkKOJyHKQeE+2jszfLk8nHE0j5SG7aSFMb8iNOkZZFu8SF6fR792q9OJ+p7J5/TKVaqUjBEyZb46QENGWswMCRjaxKEpm8sjboRrs9PElqhwRAT9S1/bK3mm+0gZShHgrgDn1OoV65Q50OUXBkaVkIWEQYTAeeHZl+tli/ppAjPkeYqxxJx2CpCtV4ovrZTZ9UpTGNAVQXXGbaHsbUxttQdAJGBVPllgXshIseLhHd+ZVRPNEXO30iHGeeaV67TtJcEf2i8Ogdi/YezBTSsMUFjP5csuOo6irxqw1/i6k2/Ly8Nw1LGYDm52EUkzg4/dbCfFGlMnuHEilH8l68IzmOw+GViEqfxJB7ca/65669+sQHRMa0m57iaRvudEI5sZUJr+UicOh6u4vrDvDcOqDoBorN0qf1sefkOFala6mGXu3Uy8mtRYOtqO7IgNrcywIjzUA3pB298QFhUzj8bhmzYww9/wytqY3CGAA6vZFd00CNxY0SSkMfJZjPecgw3l8MIbfQ9sYH9+MQziUl91ZpCFSUnYt3fSIby5gdD/8KJGD91KBGxspjPMbkZkNa1B6HxU6Z99kQcSF6/Y/6k4XuZRf6WIvy6V0T1bXSUA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
