appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: PtfCRF3/kp8uW43HijEFmCPUHJasxh6cByRU3A+t6NZLQXzZirLu0w2IoLpLxRoYCHMxFB8h0/ASzl5V9PjLRC2A1f4o4nFTBWBancAGYnqq8+hsciVW19fJ3G6su1hLrozens45IABIZhBDG7V5D9Sw9X6Flu2QyPl5duWdPLJ904DGbrZ6hglE1uwl6+R8TKWOyNEWs7sXDIIRbTQZdUBc3hHnCjHERliBfuwfJuwLZD6TF4bPW4dt7J0nBmmNvQvUVyxkXdgiFWfJLxIEiL9ET9sn1nQb5QNfOzvD1tJ1j8fskaR8Ak7WbuTuIhnSgFh6Icsf11+YfHtuB8a66V06+PI/1GL3Ivk1HqJIvCVp3XQO0EhJqLB1lQ2iaraw1BBEze7+i8iSj/6Qwj9CWGFvi0aFQoMWrLyRKbQ6pJLf8xREB2q1JRzIh1o92VyatUULTDJfzgokwmV/KdzxXL8+xI6TwjlqhStgjd3kaPB015jliEUVQBtzfPcP9YwHFJ++FaioSF/aJBy7UX8/HdyEYLDRA8J1GVHdu38fQnwCDWHhaKPBMrJlPOBLpi+2VSOcbsB0smhEqF1ry+AU7s9CTgidxDs5CtM+Y+ONZALb7uBSCX0RvOO1yE4i/1fZ/UbZECz/r5xCW+hGz5IaJJVkIh3QoJfElB56H6ATt0o=}
provider:
  win: azure
